name: zookeeper
base: core22
version: '3.6.4'
summary: Apache Zookeeper in a snap.
description: |
  ZooKeeper is a centralized service for maintaining configuration 
  information, naming, providing distributed synchronization, and 
  providing group services.

grade: stable
confinement: strict

apps:
  init:
    command: with_config.sh bin/zkServer-initialize.sh
  cli:
    command: with_config.sh bin/zkCli.sh
  daemon:
    command: with_config.sh bin/zkServer.sh start
    plugs: [network, network-bind, removable-media]
    install-mode: disable
    daemon: forking
    stop-command: with_config.sh bin/zkServer.sh stop
  status:
    command: with_config.sh bin/zkServer.sh status

parts:
  zookeeper:
    plugin: nil
    source: https://dlcdn.apache.org/zookeeper/zookeeper-${SNAPCRAFT_PROJECT_VERSION}/apache-zookeeper-${SNAPCRAFT_PROJECT_VERSION}-bin.tar.gz
    stage-packages:
    - openjdk-8-jre-headless
    override-build: |-
      snapcraftctl build
      sed -i "s:dataDir=/tmp/zookeeper:dataDir=/var/snap/zookeeper/common:g" conf/zoo_sample.cfg
      echo "dataLogDir=/var/snap/zookeeper/common" >> conf/zoo_sample.cfg
      sed -i "s:zookeeper.log.dir=.:zookeeper.log.dir=/var/snap/zookeeper/common/logs:g" conf/log4j.properties
      sed -i "s:zookeeper.root.logger=INFO, CONSOLE:zookeeper.root.logger=INFO, CONSOLE, ROLLINGFILE, TRACEFILE:g" conf/log4j.properties
      sed -i "s:zookeeper.log.threshold=INFO:zookeeper.log.threshhold=DEBUG:g" conf/log4j.properties
      cp -r ./* $SNAPCRAFT_PART_INSTALL
    override-prime: |-
      snapcraftctl prime
      rm -vf usr/lib/jvm/java-8-openjdk-amd64/jre/lib/security/cacerts
  wrapper:
    plugin: dump
    source: snap/local
