name: charmed-zookeeper
base: core22
version: '3.6.4'
summary: Apache Zookeeper in a snap.
description: |
  This is a snap that bundles Apache ZooKeeper together with other tools of its ecosystem in order to be used in Charmed Operators, providing automated operations management from day 0 to day 2 on the Apache ZooKeeper distributed coodrdinator, on top of a Virtual Machine cluster and K8s cluster. It is an open source, end-to-end, production ready data platform on top of cloud native technologies.
grade: stable
confinement: strict

system-usernames:
  snap_daemon: shared

hooks:
  install:
    plugs:
      - network
      - network-bind

environment:
  JAVA_HOME: ${SNAP}/usr/lib/jvm/java-8-openjdk-amd64/jre
  ZOO_LOG_DIR: ${SNAP_COMMON}/var/log/zookeeper
  ZOO_LOG4J_PROP: INFO,CONSOLE,ROLLINGFILE
  ZOO_LOG_FILE: zookeeper.log
  ZOOCFGDIR: ${SNAP_DATA}/etc/zookeeper

apps:
  daemon:
    command: opt/zookeeper/with_config.sh bin/zkServer.sh start-foreground
    plugs:
      - network
      - network-bind
      - removable-media
    install-mode: disable
    daemon: simple
  keytool:
    command: usr/lib/jvm/java-8-openjdk-amd64/bin/keytool

slots:
  logs:
    interface: content
    source:
      read: 
        - $SNAP_COMMON/var/log/zookeeper

parts:
  zookeeper:
    plugin: nil
    source: http://archive.apache.org/dist/zookeeper/zookeeper-${SNAPCRAFT_PROJECT_VERSION}/apache-zookeeper-${SNAPCRAFT_PROJECT_VERSION}-bin.tar.gz
    stage-packages:
    - openjdk-8-jre-headless
    - util-linux
    - curl
    override-build: |-
      snapcraftctl build
      cp -r ./* $SNAPCRAFT_PART_INSTALL
    override-prime: |-
      snapcraftctl prime
      rm -vf usr/lib/jvm/java-8-openjdk-amd64/jre/lib/security/cacerts
      mkdir -p $SNAPCRAFT_PART_INSTALL/opt/zookeeper
  prometheus-exporter:
    plugin: nil
    after: [zookeeper]
    override-build: |
      curl -o jmx_prometheus_javaagent.jar "https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/0.17.0/jmx_prometheus_javaagent-0.17.0.jar"
      EXPECTED_SHA="48ab23a7514f9de5d2ca0acbb8ed1573b3c2ecbef7c5dc4d37c4ba125e538199"
      JAR_SHA=$(sha256sum jmx_prometheus_javaagent.jar | cut -d " " -f1)
      if [ $JAR_SHA != $EXPECTED_SHA ]; then exit 1; fi
      cp jmx_prometheus_javaagent.jar $SNAPCRAFT_PART_INSTALL/
    organize:
      jmx_prometheus_javaagent.jar: opt/zookeeper/jmx_prometheus_javaagent.jar
  wrapper:
    plugin: dump
    source: snap/local
