name: Build and Test

on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    name: Build snap
    uses: canonical/data-platform-workflows/.github/workflows/build_snap.yaml@v41.1.0

  test:
    name: Test Snap (${{ matrix.system.arch }})
    runs-on: ${{ matrix.system.os }}
    timeout-minutes: 90
    needs:
      - build
    strategy:
      matrix:
        system:
          - os: ubuntu-22.04
            arch: amd64
          - os: ubuntu-22.04-arm
            arch: arm64
    name: Test Snap
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Download snap file
        uses: actions/download-artifact@v6
        with:
          pattern: ${{ needs.build.outputs.artifact-prefix }}-*
          merge-multiple: true

      - name: Install snap file
        run: |
          FILE=$(ls -1 *${{ matrix.system.arch }}.snap | tail -n1)
          sudo snap install $FILE --dangerous

      - name: Set default config
        run: |
          sudo mkdir -p /var/snap/charmed-zookeeper/current/etc/zookeeper
          sudo cp /snap/charmed-zookeeper/current/opt/zookeeper/conf/zoo_sample.cfg /var/snap/charmed-zookeeper/current/etc/zookeeper/zoo.cfg

      - name: Start snap services
        run: |
          sudo snap start charmed-zookeeper.daemon
          sleep 5

      - name: Check zookeeper up
        run: |
          echo srvr | nc localhost 2181

      - name: Check keytool
        run: |
          charmed-zookeeper.keytool

      - name: Check transaction-log-toolkit
        run: |
          charmed-zookeeper.transaction-log-toolkit -h
