name: Operator Tests

on:
  pull_request:
  workflow_call:
  workflow_dispatch:

jobs:
  build-and-publish:
    uses: ./.github/workflows/publish.yaml
    with:
      release: ${{ github.base_ref }}/${{ github.ref_name }}
  vm-integration:
    runs-on: ubuntu-latest
    needs: build-and-publish
    strategy:
      matrix:
        env:
          - vm-integration
          - vm-integration-provider
          - vm-integration-scaling
          - vm-integration-tls
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          provider: lxd
          # This is needed until
          # https://bugs.launchpad.net/juju/+bug/1977582 is fixed
          bootstrap-options: "--agent-version 2.9.29"
      - name: Install tox
        run: python3 -m pip install tox
      - name: Integration Tests
        run: tox -e ${{ matrix.env }}
