on:
  workflow_dispatch:

jobs:
  get-versions-diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: versions-diff
        run: |
          pip install -r requirements.txt
          ./check_updates.py | jq -R -s -c 'split("\n")[:-1]'
          echo "::set-output name=matrix::$(./check_updates.py | jq -R -s -c 'split("\n")[:-1]')"
    outputs:
      matrix: ${{ steps.versions-diff.outputs.matrix }}
  
  create-branch:
    runs-on: ubuntu-latest
    needs: get-versions-diff
    strategy:
      matrix:
        versions: ${{ fromJson(needs.get-versions-diff.outputs.matrix) }}
    steps:
      - uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: ${{ matrix.versions }}/stable
          sha: '${{ github.event.pull_request.head.sha }}'
      - name: clone
        uses: actions/checkout@v3
        with:
          ref: ${{ matrix.versions }}/stable
      - name: inject-version
        run: |
          sed -i "s:3.6.3:${{ matrix.versions }}:g" snap/snapcraft.yaml
          grep version snap/snapcraft.yaml
      - name: commit
        run: |
          git config user.name "GitHub Actions"
          git config user.email noreply@github.com
          git add snap/snapcraft.yaml
          git commit -m "Prepare release of version ${{ matrix.versions }}/stable"
      - name: push
        run: git push origin ${{ matrix.versions }}/stable
  
  publish:
    runs-on: ubuntu-latest
    needs:
      - create-branch
      - get-versions-diff
    strategy:
      matrix:
        versions: ${{ fromJson(needs.get-versions-diff.outputs.matrix) }}
    steps:
    - uses: actions/checkout@v2
    - uses: snapcore/action-build@v1
      id: build
    - uses: snapcore/action-publish@v1
      env:
        SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
      with:
        snap: ${{ steps.build.outputs.snap }}
        release: stable

  open-issue:
    runs-on: ubuntu-latest
    if: failure()
    needs: 
      - create-branch
      - get-versions-diff
      - publish
    permissions:
      contents: read
      issues: write 
    strategy:
      matrix:
        versions: ${{ fromJson(needs.get-versions-diff.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v2
      - uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_TITLE: ${{ matrix.versions }}
