name: Publish new ZooKeeper SNAP revision

on:
  push:
    branches:
      - "3/[a-z]+"
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  get-track:
    name: Get track
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      track: ${{ steps.track.outputs.track }}
    steps:
      - id: track
        name: Derive track from branch
        run: echo "track=${GITHUB_REF_NAME%%/*}" >> "$GITHUB_OUTPUT"
    permissions: {}

  build:
    name: Build snap
    uses: canonical/data-platform-workflows/.github/workflows/build_snap.yaml@v50.2.0

  release:
    name: Release snap
    needs:
      - get-track
      - build
    uses: canonical/data-platform-workflows/.github/workflows/release_snap_edge.yaml@v50.2.0
    with:
      track: ${{ needs.get-track.outputs.track }}
      artifact-prefix: ${{ needs.build.outputs.artifact-prefix }}
    secrets:
      snap-store-token: ${{ secrets.SNAP_STORE_TOKEN_EDGE }}
    permissions:
      contents: write # Needed to create GitHub release
