on:
  push:
    branches:
      - '[0-9]+.[0-9]+/*'
    inputs:
      release:
        description: Release for snap formatted track/risk/channel
        required: true
        type: string
  workflow_call:
    inputs:
      release:
        description: Release for snap formatted track/risk/channel
        required: true
        type: string
  workflow_dispatch:
    inputs:
      release:
        description: Release for snap formatted track/risk/channel
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: snapcore/action-build@v1
        id: build
      - uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
        with:
          snap: ${{ steps.build.outputs.snap }}
          release: ${{ inputs.release }}
