name: Publish new ZooKeeper SNAP revision

on:
  push:
    branches:
      - "3/[a-z]+"
  workflow_call:
  workflow_dispatch:

jobs:
  checks:
    name: Check Metadata and branch consistency
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v6

      - id: get-current-version
        name: Retrieve Metadata
        run: |
          VERSION=$(yq '(.version|split("-"))[0]' snap/snapcraft.yaml)
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

          BRANCH=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
          echo "branch=${BRANCH}" >> $GITHUB_OUTPUT
          echo "risk=${BRANCH##*\/}" >> $GITHUB_OUTPUT
          echo "track=${BRANCH%*\/*}" >> $GITHUB_OUTPUT

      - name: Check consistency between metadata and release branch
        run: |
          MAJOR_VERSION=$(echo ${{ steps.get-current-version.outputs.version }} | sed -n "s/\(^[0-9]*\).*/\1/p")
          if [ "${MAJOR_VERSION}" != "${{ steps.get-current-version.outputs.track }}" ]; then exit 1; fi
        continue-on-error: false

  build:
    name: Build snap
    uses: canonical/data-platform-workflows/.github/workflows/build_snap.yaml@v41.1.0

  release:
    name: Release snap
    needs:
      - build
      - checks
    uses: canonical/data-platform-workflows/.github/workflows/release_snap.yaml@v41.1.0
    with:
      channel: ${{ needs.release_checks.outputs.track }}/${{ needs.release_checks.outputs.risk }}
      artifact-prefix: ${{ needs.build.outputs.artifact-prefix }}
    secrets:
      snap-store-token: ${{ secrets.SNAP_STORE_TOKEN }}
    permissions:
      contents: write # Needed to create GitHub release
