on:
  push:
    branches:
      - '[0-9]+.[0-9]+/*'
  schedule:
    - cron: '0 12 * * 3'
  workflow_call:
  workflow_dispatch:

inputs:
  release:
    description: Release for snap formatted track/risk/channel
    required: true
    default: ${{ github.ref_name }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: snapcore/action-build@v1
        id: build
      - uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
        with:
          snap: ${{ steps.build.outputs.snap }}
          release: $INPUT_RELEASE
