#!/usr/bin/env bash

set -eux

export COMPONENT=zookeeper

export CONF="${SNAP_DATA}"/conf
export LOGS="${SNAP_COMMON}"/logs
export DATA="${SNAP_COMMON}"/data
export BINARIES="${SNAP}"/opt/$COMPONENT

mkdir -p $CONF
mkdir -p $LOGS
mkdir -p $DATA
mkdir -p $BINARIES

cp "${SNAP}"/opt/$COMPONENT/conf/* $CONF

chmod -R 770 "${SNAP_DATA}"/*
chmod -R 770 "${SNAP_COMMON}"/*

chown -R snap_daemon "${SNAP_DATA}"/*
chown -R snap_daemon "${SNAP_COMMON}"/*
